### ISSUE TITLE
Notes in vextab overlap and bump into each other

### ISSUE THREAD

**Issue by JakubBilski** [JakubBilski/tonations-recognition#58]

**Comment by AnnaMBuchman** [comment]
I think is because letters over notes

**Comment by JakubBilski** [comment]
Ur right
"Sto lat" with chords above notes:
![image](https://user-images.githubusercontent.com/47048420/103919910-ea782100-5110-11eb-9756-46da6d833f13.png)

vs without:
![image](https://user-images.githubusercontent.com/47048420/103919752-b4d33800-5110-11eb-8acd-47bd67a46c70.png)
