### ISSUE TITLE
Bug with do_szopy_D.wav file

### ISSUE THREAD

**Issue by AnnaMBuchman** [JakubBilski/tonations-recognition#71]

**Comment by JakubBilski** [comment]
I was unable to reproduce this

**Comment by AnnaMBuchman** [comment]
I got another cause of it
![obraz](https://user-images.githubusercontent.com/34186018/103832818-96712c00-507f-11eb-9884-6760f238f4f0.png)

**Comment by AnnaMBuchman** [comment]
Jezus_malusienki_Ais.wav also
